name: Learning GitHub Script

on: 
  issues:
    tpyes: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Script
      uses: actions/github-script@0.8.0
      with:
        github-toke: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
            })
            
